// Generated by CoffeeScript 1.6.3
(function() {
  var Tranny, data, div, expect, precision;

  Tranny = window.Tranny;

  expect = chai.expect;

  div = document.getElementById('test');

  precision = 100000;

  data = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]];

  mocha.setup('bdd');

  describe('constructor', function() {
    return it('adds data that is passed when intialized to its model', function() {
      var actual, tranny;
      tranny = new Tranny(data);
      actual = tranny.model.get('matrix');
      return expect(actual).to.deep.equal(data);
    });
  });

  describe('matrix', function() {
    it('should add valid data to its instance model', function() {
      var actual, tranny;
      tranny = new Tranny;
      tranny.matrix(data);
      actual = tranny.model.get('matrix');
      return expect(actual).to.deep.equal(data);
    });
    return it('should throw an error when intialized with an invalid array', function() {
      var fn;
      fn = function() {
        return new Tranny('bad');
      };
      return expect(fn).to["throw"](Error);
    });
  });

  mocha.run();

}).call(this);
