// Generated by CoffeeScript 1.6.3
(function() {
  var izzy, subject, subjects, type;

  izzy = require('../izzy');

  subjects = {
    array: [],
    boolean: false,
    defined: NaN,
    "function": function() {},
    "null": null,
    number: 42,
    object: {},
    string: 'bar'
  };

  for (type in subjects) {
    subject = subjects[type];
    exports[type] = function(test) {
      var innersubject, innertype;
      for (innertype in subjects) {
        innersubject = subjects[innertype];
        test.strictEqual(izzy[type](innersubject), type === innertype);
        test.strictEqual(izzy(type, innersubject), type === innertype);
      }
      return test.done();
    };
  }

}).call(this);
