// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.config.init({
      coffee: {
        compile: {
          files: {
            'tranny.js': 'tranny.coffee'
          }
        }
      },
      uglify: {
        options: {
          mangle: {
            toplevel: true
          },
          compress: {
            dead_code: true,
            unused: true,
            join_vars: true
          },
          comments: false
        },
        standard: {
          files: {
            'tranny.min.js': ['tranny.js']
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    return grunt.registerTask('default', ['coffee', 'uglify']);
  };

}).call(this);
